version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - url-shortener-network

volumes:
  redis_data:

networks:
  url-shortener-network:
    driver: bridge 