{
 "title": "Metrics endpoint",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Redirects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(url_redirects_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=\"201\"}[5m])) / sum(rate(http_requests_total[5m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Shortened URLs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 16 },
   "targets": [
    { "expr": "url_shortening_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 6, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])" }
   ]
  },
  {
   "title": "Active URLs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 29 },
   "targets": [
    { "expr": "active_urls", "legendFormat": "__auto" }
   ]
  }
 ]
}